[tool.black]
target-version = ['py39']
exclude = '.git/'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
known_first_party = ['ui24r_client']

[tool.mypy]
# By default, use strict type checking for every package.
ignore_missing_imports = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
mypy_path = './stubs'
warn_redundant_casts = true
